name: Build And Run Test on Mac

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

jobs:
      
  Build_And_Run_UnitTest:
    name: Build and Run Unit Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install gcc
      run: brew install gcc@8
        
    - name: Update Path
      run: |
        echo "brew --prefix llvm)/bin" >> $GITHUB_PATH
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python3 -m pip install --upgrade wheel

    - name: Update setup.py
      run: python3 -m pip install --upgrade setuptools

    - name: Install pytest
      run: python -m pip install pytest

    - name: Install filepattern
      working-directory: ${{github.workspace}}
      run: python3 -m pip install .

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/